class DataFrame: ...
class Series: ...

class Timestamp:
    def __init__(self, value: object = ...) -> None: ...
    def normalize(self) -> Timestamp: ...
    def strftime(self, format: str) -> str: ...

def isna(obj: object) -> bool: ...
