from typing import Any

class DataFrame:
    columns: Any
    index: Any
    loc: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def merge(self, *args: Any, **kwargs: Any) -> Any: ...
    def rename(self, *args: Any, **kwargs: Any) -> Any: ...
    def reset_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def sort_values(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_dict(self, *args: Any, **kwargs: Any) -> Any: ...

class Series:
    dt: Any
    empty: bool

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def max(self, *args: Any, **kwargs: Any) -> Any: ...

class Timestamp:
    def __init__(self, value: object = ...) -> None: ...
    def isoformat(self) -> str: ...
    def normalize(self) -> Timestamp: ...
    def strftime(self, format: str) -> str: ...

def isna(obj: object) -> bool: ...
def to_datetime(obj: object, *args: Any, **kwargs: Any) -> Any: ...
def to_numeric(obj: object, *args: Any, **kwargs: Any) -> Any: ...
